### ISSUE TITLE
implement sin function

### ISSUE THREAD

**Issue by GregHilston** [GregHilston/github-tutorial-calculator#7]
It'd be nice to have a function that would calculate the sine of whatever is passed in. Can someone write this please?

```
def sin(x):
"""Returns the sine value of x
"""
```

Perhaps write some tests too?

**Comment by dcerman** [comment]
I got this.

**Comment by AFewMistakesAgo** [comment]
I was going to do this but looks like it has been done? I suspect this issue can be closed.

**Comment by GregHilston** [comment]
@AFewMistakesAgo This has been implemented. I will close the issue, thank you!
